_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: Brain Tumor Segmentation
hidden_size:
    value: 128
learning_rate:
    value: 0.001
model:
    value: UNet
num_epochs:
    value: 50
optimizer:
    value: Adam
scheduler:
    value: StepLR
